project:
  type: manuscript

lang: de

manuscript:
  article: index.qmd
  
execute:
  freeze: auto

format:

  html:
    theme: flatly

    gfm: default
  # typst:
  #   toc: true
  #   toc-depth: 3
  #   number-sections: true
  #   section-numbering: 1.1.1
  #   lang: de
  #   fig-align: center
  #   bib: references.bib
  #   papersize: a4
  #   output-file: ans_bericht 



#  epub:
#    theme: flatly
#    output-file: ans_bericht
